[project]
name = "mensa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gouthaman-b", email = "gouthaman.b@outlook.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
mensa = "mensa:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 79
target-version = "py310"